services:
  backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "8000:8000"
    env_file:
      - backend/.env  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: ai-frontend
