version: "3.9"
services:
  backend:
    build: ./backend
    container_name: ai-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "3000:80" 
